### PR TITLE
Empty All button also

### PR DESCRIPTION
**Pull request by ankitest**
without additional gray line at the top of the bottom widget

### CODE REVIEW

**Comment by Arthaey** [comment]
Thank you for the PR! I'm not going to merge this as-is, but I've taken several of your suggested changes and included them in the latest version of this addon (commit eff9d2a5)

One particular change I did not include was the monkeypatch of drawButtons, because I don't want my addon to delete any buttons that other addons might have added before me.

**Comment by ankitest** [comment]
_Do not monkey patch_ is a good idea. But there is one problem with the decision here:  
one extra line over the buttons. 

You can install [' View HTML source with JavaScript and CSS styles](https://ankiweb.net/shared/info/1128123950) 1128123950 add-on  
then restart Anki and use new menu command `Cards` -> `View bottomWeb Source`   

You will see the code (here is it without huge jQuery script):  

```
<html class=" webkit safari win js webkit safari win js">
<head>
<style>
button {
font-weight: normal;
}

#header {
margin:0;
margin-top: 4px;
font-weight: bold;
}

html {
height: 100%;
background: -webkit-gradient(linear, left top, left bottom,
  from(#ddd), to(#fff));
margin:0; padding:0;
}

body {
margin:0; padding:0;
position:absolute;
top:0;left:0;right:0;bottom:0;
-webkit-user-select: none;
border-bottom: 1px solid #aaa;
}

* { -webkit-user-drag: none; }

.hitem {
padding-right: 6px;
text-decoration: none;
color: #000;
}
.hitem:hover {
text-decoration: underline;
}

#header {
background: -webkit-gradient(linear, left top, left bottom,
from(#fff), to(#ddd));
border-bottom: 0;
border-top: 1px solid #aaa;
margin-bottom: 6px;
margin-top: 0;
}
</style>
</head>
<body class="">
<center><table width="100%" height="100%" id="header"><tbody><tr><td align="center">
<style>
button {
font-weight: normal;
}

#header {
margin:0;
margin-top: 4px;
font-weight: bold;
}

html {
height: 100%;
background: -webkit-gradient(linear, left top, left bottom,
  from(#ddd), to(#fff));
margin:0; padding:0;
}

body {
margin:0; padding:0;
position:absolute;
top:0;left:0;right:0;bottom:0;
-webkit-user-select: none;
border-bottom: 1px solid #aaa;
}

* { -webkit-user-drag: none; }

.hitem {
padding-right: 6px;
text-decoration: none;
color: #000;
}
.hitem:hover {
text-decoration: underline;
}

#header {
background: -webkit-gradient(linear, left top, left bottom,
from(#fff), to(#ddd));
border-bottom: 0;
border-top: 1px solid #aaa;
margin-bottom: 6px;
margin-top: 0;
}
</style>

<center><table width="100%" height="100%" id="header"><tbody><tr><td align="center">

<button title="" onclick="py.link(&quot;shared&quot;);">Partages</button>
<button title="" onclick="py.link(&quot;create&quot;);">Créer un paquet</button>
<button title="Raccourci&nbsp;: Ctrl+I" onclick="py.link(&quot;import&quot;);">Importer</button><button title="Rebuild All" onclick="py.link(&quot;rebuildDyn&quot;);">Rebuild All</button><button title="Empty All" onclick="py.link(&quot;emptyDyn&quot;);">Empty All</button></td></tr></tbody></table></center>
</td></tr></tbody></table></center>
</body>
</html>
```

What do you see? Double STYLE section, double CENTER and TABLE.  

Why it is so? You are taking the whole HTML code of the bottom widget,  
inserting additional buttons into it and putting it back via `bottom.draw()`

What does it mean? It means that `bottom.draw()` waits as parameter  
only the buttons code, not the whole HTML again.

**Comment by ankitest** [comment]
You can find the code in the end of `aqt\toolbar.py`:  

```
    def draw(self, buf):
        self.web.show()
        self.web.stdHtml(
            self._centerBody % buf,
            self._css)
```

https://github.com/dae/anki/blob/master/aqt/toolbar.py#L128-L149

**Comment by ankitest** [comment]
A year and a half ago I didn't know how to achieve buttons code   
and simply create a new command  in `Tools` menu with `Ctrl+Shift+F` hotkeys  
in [' Must Have](https://ankiweb.net/shared/info/67643234) 67643234 addon.

Thank you for the pretty nice `Rebuild All` idea!

**Pull request closed without merging**
